#include "ParserWrapper.hpp"
#include "Parser.hpp"
#include "Ast.hpp"
// The parser entry point, generated by Bison.
// extern "C" int yyparse(void *);
int yyparse(ParserWrapper *);

ParserWrapper::ParserWrapper()
{
}

ParserWrapper::~ParserWrapper()
{
}

int 
ParserWrapper::Parse(std::istream *stream, const char *filename)
{
    _lexer.switch_streams(stream, 0);
    _filename = filename;

    int status = yyparse(this);

    return status;
}
